"""Generate a sanitized, public-safe snapshot of the dashboard for a portfolio
showcase.

Privacy model: we NEVER expose real capital. Every dollar figure in the app is
linear in trade *size*, so we scale the ledger's quantity/commission by a single
factor k chosen to normalize the live book to a fixed notional (DEFAULT $100k).
Percentages, Sharpe/Sortino and win-rate are ratios -> invariant to k, so the
real skill signal is preserved exactly while the true dollar scale is hidden.

We also:
  - run fully OFFLINE from the local ledger (no IBKR token, no live fetch),
  - drop raw position sizes (share counts + $ value) in favor of weight %,
  - clear warnings and account-level TWR (which could leak absolute NAV).

Output: demo/demo_data.js  (a `window.DEMO = {usd, sgd}` blob the static page
reads). Safe to commit and deploy as a static site.

Run:  IBKR_TOKEN is not needed.
      /path/to/python make_demo.py
"""
import os, sys, json

# config.py requires IBKR_TOKEN at import time; set a throwaway value since we
# patch out every network call below and never actually use it.
os.environ.setdefault("IBKR_TOKEN", "demo-not-used")

ROOT = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, ROOT)

import pandas as pd
import app.dashboard as D
from data.ledger import load_ledger

TARGET_NOTIONAL = 100_000.0   # the fictional book size everything is scaled to

REAL = load_ledger()
if REAL.empty:
    raise SystemExit("No trade_ledger.csv found - run the pipeline/backfill first.")

_STATE = {"k": 1.0}


def _scaled_ledger(*_a, **_kw):
    """Stand-in for merge_trades: return the local ledger with size scaled by k.
    Scaling quantity AND commission keeps per-share economics identical while
    every downstream dollar amount scales by k."""
    lg = REAL.copy()
    for col in ("quantity", "commission", "proceeds", "realized_pnl"):
        if col in lg.columns:
            lg[col] = lg[col] * _STATE["k"]
    return lg


# --- neutralize all live/network + persistence paths in the pipeline ---
D.fetch_flex_report = lambda *a, **k: "<FlexQueryResponse/>"
D.parse_trades = lambda _xml: pd.DataFrame()
D.filter_stock_trades = lambda df: df
D.merge_trades = _scaled_ledger
D.parse_change_in_nav = lambda _xml: None   # -> twr None (no absolute NAV leak)


def build(ccy):
    return D.build_dashboard_payload(ccy)


def sanitize(payload, ccy):
    """Strip absolute position sizes; express holdings as portfolio weight %."""
    valkey = f"value_{ccy}"
    total = sum(float(p.get(valkey) or 0) for p in payload["positions"]) or 1.0
    for p in payload["positions"]:
        p["weight_pct"] = round(float(p.get(valkey) or 0) / total * 100, 1)
        p.pop("quantity", None)
        p.pop(valkey, None)
    payload["warnings"] = []
    payload["twr"] = None
    return payload


# Pass 1: real scale, just to read the current book value -> pick k.
_STATE["k"] = 1.0
probe = build("usd")
book = sum(float(p.get("value_usd") or 0) for p in probe["positions"])
if book <= 0:
    buys = REAL[REAL["action"].str.upper() == "BUY"] if "action" in REAL else REAL
    book = float((buys["quantity"].abs() * buys["price"]).sum()) or 1.0
_STATE["k"] = TARGET_NOTIONAL / book

# Pass 2: build both currencies at the normalized scale, then sanitize.
payloads = {ccy: sanitize(build(ccy), ccy) for ccy in ("usd", "sgd")}

OUT_DIR = os.path.join(ROOT, "demo")
os.makedirs(OUT_DIR, exist_ok=True)
out = os.path.join(OUT_DIR, "demo_data.js")
with open(out, "w") as f:
    f.write("// Auto-generated by make_demo.py - sanitized snapshot, no real capital.\n")
    f.write("window.DEMO_NOTIONAL = %d;\n" % int(TARGET_NOTIONAL))
    f.write("window.DEMO = " + json.dumps(payloads, separators=(",", ":")) + ";\n")

print(f"Wrote {out}")
print(f"  scale factor k = {_STATE['k']:.6g}  (real book normalized to ${int(TARGET_NOTIONAL):,})")
print(f"  usd metrics: {json.dumps(payloads['usd']['metrics'])}")
print(f"  {len(payloads['usd']['trades'])} trades, {len(payloads['usd']['positions'])} positions")
